language: scala
scala: 2.12.8
jdk: openjdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier/cache

env:
  global:
    - COURSIER_PROGRESS=0
    - SBT=./sbt
    # ENCRYPTION_PASSWORD
    - secure: kBCQV8r0XQ+Bpma/f0rrqLiX1aEN2hLT19F3Wdu0iqqYtxLYKMIKm/ZLO9sti7c4wXQwZqG4G/SSVlQwydAGfiST+ixS3LC7RQZao5BJyfS2ZxuCYc+TWqO87LUwWAEyS2RTXAvv64YIqDocwK3at7FRrCsuwx4Bzh5jfMXFiJvmYb3zS/CX6pA1gdcVEoW0X59JTLFSCI3k4o8eumZKGglIcaCHp8HNXfs5URmoX6NgGx3bJKLuA063Eab8+uyLvQnKv/62KKdIJQNZHEaSMCOjqWqZc/xUcnvS7EtfT15mM3tMAHegotZ9h/Dt1et8WwufNrLV9J6Pp4cDvSDiehc+j3h4MzNsog4K5htFddzmWpzKvm8Vi1Sv6oe5gb6rrRSRGrRIzh7dZ5EqPdsKZdS4ioDmimw1W7L4jHURTcabdS4oaTIRfXVIlPkqy39nONVLVePtr+NvIqyp1GY+ZJCm9bN1XeHszy2AsL2apFmmXvgJoLaGjSMVEaRJkj9HKvWHleQWmqvVnSX8+9vGqz45zERf204pBSKX8HxTpDRj8hKk/NykQTIbK3by8W5o6uBFgvjIrRu4KsUWlInUIWPaTiFD4aK7ZUC2n/kJlGBJN2zLDTgYTMPOBS4Q0XAFYz74khDaqukLOvYrlZt0tzOpvbVHork0vPtQRWQS/Xc=
    # GITHUB_TOKEN
    - secure: Q6rWejjnWmVEAXcpmZcdnmvqR7UYpWv5jI6vdb3pFhq3iy4XW8LgocmHshI/Ri4C7Sz1M1BylZOukiaUww1Rc5I9U+UFDBxa25z71H4ED8nPJG7tGSxeForMvcQbQsGR1MpkVcfDpHThTFq7xzQ1bNS/y+UqE6J7DXNXgctNO8IvDQl0DoNCyP84/COtlfGUeGGjaG+Jgt28oHfWDELF+IcBqR5zQPxOP8rNdSqLd9Ro2yXYqIHFaKhNtvZ5gDPNlINkh0MmnDXXb1WXTLIb0Pj7JzENQRatBsTHLAmzxhfou67VU1bBMVfi5d4mPvgTmFUTzEGnM8utFQcDHYfajPmS3u9Cj3b0y0BTOGhdTo54LGGLXkIlFQ08ES3Lq09CN3y0Le0sqxTwV9FVxt7o0tOU5LxCj9+UQIJTlXZvPLa8DnMqtHiOdA/QwIBuQ6FSye72nNJn5S9cvLa48w9Db8xhdoaWEsSE92LDCaXQnt0s38EakGl0deEHH1vrNvkZ6F/c/88sAcvdFzIqb6RjfxpgaY9bo/1MDQazPYxyG0DDPFaqj5WfK8QDWqocRJPE1shNypipP2R60okYV0UY4TXHC0K3H1Rmi9ItD58PSLZ65nfy+A/UjhEeniMHdo+cr0grbMcxh+f4nJcW506D/iEwGZPAJpFkEPQPzpJQNQ8=
    # GITHUB_ACCESS_TOKEN
    - secure: aL7I+/AaR6GZB7uvnr8u5/VIX0+GD+7NM+2euHhuLQltvPHupf+2M2dqfMsfgYJ9JKTQCjOO8xkjpUQqA7ljkytJpexiC2lkegm2D9LNeGUpl4cK86hDaLfyw5Nnc5Bm/tBfySgOx9eWf4Qxl0XzLy+BPsjA2xFC3Xg6pwYml+0XNNbWiezIyBy5ZJgBMmY1v4t0S8KMgg5vVpXQwDiwPy02MKDgCjDXlhqE632wOQlJIGZMLMqCAjtvFL/BA6u/HiVmvd8mv/bM2ZNnFSNuA6JU/R7Os3zp9J0qb6gpytoq2w5dyQNT43iIze5QfHi8CWmKfgj8ZtQqIQisbxtZYEIYJ8kMcmqEEUUa9CyZlKyavXaoNqpXgKeGX/eXWgjQmDGFpDN6LY9/7f6OYHAeDv1gl/X/bDq6DLohNlEgka5CfBuH4nH8Y+nc6DYkBonuwPLDd4HYX6dZP5Xw1D3iXYH1EuQn+MReUoJ+jrLt/ThPmVJEClbibfme5Vx16O1Ley9p/KE8XxOv9iu/FTIsegXKFpIgyMcoKoJv14AtmBhdtN47tTabSi4D+06r5Q/XVsZDC8oFz6y+BxsAop76Eo/K/cXispVxCQKS1s9bta5gdKAC6bQI5YxyjPEMoZpY8aJnpHk/23ikz4PrkOEjmUVIzQYRyjaLOTULebe485A=
    # DISCORD_WEBHOOK_TOKENS
    - secure: C8maw1uOvvneGgfIS6/wbKOWTDedUpt23ZMy8maMa2JpD4FGY+TDVB+hPJ1Mw7MpDMJEeyw2kC2IjMpxTaBsYtWvKxVIzvX4kRJ6LPRMLRXotOTjK0uWUIA6izHT1+hZxEdb2m5z3zz/oyORldFaIwaI5ugRB9NbVJyRdUgT32Kw3AmPiiDMm7kVA61yQPcWNHAmj05Jhey5BdZr/WTOgOKxXFWI/4Bwvu8O88tKzQyFOg8CNNtNBn2EiSZgCwrq6qoZ3pn2zBR6J2L/kURXMQFjMEO92UJUWDqLOfYNkthwAwP3sf+uUVXr/L2nV65bEa5oyP2x1PYwLIw/H1DqRIoZbrKox5duYeJPfpeihbAea+6dvILwUvFnblC6ysQszMPoaT8/fnaiJz+2Vl731g0IC7hFHaFKbAgLxU83dUV/eOJQf8sgkTv4Qicpnkn08ndAtJWIlguVCOqqa4F6TTpPQYeOXq1LyF+4q4Jihqa5yPOy8U6HiYbruV1kNFohde3ei8JRFc+cCIN8cZrCi5how06Yae1VqSuJqXgxMxgoOy/9AQvOvBU8Yh8jbbfcZMr2Bir/FxpbUEZj5MUffiHLMt/40JVppuhQxzLjV4lgvsqA0JQOrTfBxF8ZW9S2WeG248r/abFU7EBqqRiIsrtrKC/qPsOvXd1y1BE+R+0=

install:
  - mkdir scripts
  - $SBT transferCommonResources
  - scripts/commonSetup

script:
    - set -e

    - $SBT ++$TRAVIS_SCALA_VERSION test

    - |-
      if [ $TRAVIS_PULL_REQUEST == "false" ] && [[ "$TRAVIS_BRANCH" =~ backport/v.*|master ]]; then
        $SBT transferPublishAndTagResources;
        TRAVIS_JOB_NUMBER=1 scripts/publishAndTag 'slamdata/suprem';
      fi

after_success:
  - scripts/checkAndAutoMerge
  - scripts/discordTravisPost success https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

after_failure:
  - scripts/discordTravisPost failure https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

branches:
  only:
    - master
    - /^backport.*$/

before_cache:
  - find "$HOME/.sbt/" -name '*.lock' -print0 | xargs -0 rm
  - find "$HOME/.ivy2/" -name 'ivydata-*.properties' -print0 | xargs -0 rm
